CREATE DATABASE tracks;
GRANT ALL PRIVILEGES ON tracks.* TO admin@'%' IDENTIFIED BY '1234567890' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON tracks.* TO tracks@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;